### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ghost** [neoighodaro-articles/trello-clone-vue-laravel#10]
When i click register button ，the  console says ：**bootstrap.js:279 POST http://127.0.0.1:8000/api/register 500 (Internal Server Error)
dispatchXhrRequest @ bootstrap.js:279
xhrAdapter @ bootstrap.js:118
dispatchRequest @ bootstrap.js:726
Promise.then (async)
request @ bootstrap.js:528
Axios.<computed> @ bootstrap.js:553
wrap @ bootstrap.js:1071
handleSubmit @ app.js:460
invokeWithErrorHandling @ app.js:9659
invoker @ app.js:9984
original._wrapper @ ### ### ### app.js:15337
app.js:473 Error: Request failed with status code 500
    at createError (bootstrap.js:653)
    at settle (bootstrap.js:899)
    at XMLHttpRequest.handleLoad (bootstrap.js:166)
(anonymous) @ app.js:473
Promise.catch (async)
handleSubmit @ app.js:472
invokeWithErrorHandling @ app.js:9659
invoker @ app.js:9984
original._wrapper @ app.js:15337**

**Comment by neoighodaro** [comment]
Check your Laravel log to see what the issue is



Neo Ighodaro
Software Engineer | Twitter | neoighodaro.com
