### ISSUE TITLE
Order of artisan commands

### ISSUE THREAD

**Issue by FrankyJust** [neoighodaro-articles/trello-clone-vue-laravel#4]
good tutorial! One remark: php artisan passport:install generated errors, seems that this command has to be placed after the command php artisan db:seed

**Comment by connecteev** [comment]
also before php artisan migrate

**Comment by ravisoni6262** [comment]
The correct order of commands is: 

- cp .env.example .env

- php artisan migrate

- php artisan db:seed

- php artisan passport:install

- sudo npm install

**Comment by neoighodaro** [comment]
Can you send a PR? @ravisoni6262 @connecteev @FrankyJust
